services:
  db:
    image: postgres:16.3
    environment:
      POSTGRES_USER: bikecatalog
      POSTGRES_PASSWORD: bc1234
  app:
    build:
      context: .
      dockerfile: docker/app/Dockerfile
    ports:
      - 8080:8080
    depends_on:
      - db
